name: Automation Tests on GCE

# Trigger on push to main (you can add pull_request or workflow_dispatch if desired)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo so we can copy its contents
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Create an SSH key file from the secret
      - name: Create SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/gce_key
          chmod 600 /tmp/gce_key

      # 3. Copy the entire repository to the GCE VM (user "lamhots" on ${{ secrets.GCE_IP }})
      - name: Copy code to GCE VM
        run: |
          rsync -avz --delete \
            -e "ssh -i /tmp/gce_key -o StrictHostKeyChecking=no" \
            . \
            lamhots@${{ secrets.GCE_IP }}:/home/lamhots/Automation-Tests

      # 4. SSH into the VM and install dependencies, then run the Gradle tests
      - name: Run tests on GCE VM
        run: |
          ssh -i /tmp/gce_key -o StrictHostKeyChecking=no lamhots@${{ secrets.GCE_IP }} << 'EOF'
            set -e

            # Navigate into the copied repo
            cd /home/lamhots/Automation-Tests

            # Ensure Gradle wrapper is executable
            chmod +x gradlew

            # 4.2 Run your Gradle tasks (API, Web UI, and general tests)
            ./gradlew testApi
            exit 0
          EOF

      # 5. Remove the temporary SSH key
      - name: Cleanup SSH key
        run: rm -f /tmp/gce_key