name: Automation Tests on GCE

# Trigger on push to main (you can add pull_request or workflow_dispatch if desired)
on:
  push:
    branches: [main]

jobs:
  deploy-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo so we can copy its contents
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Create an SSH key file from the secret
      - name: Create SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/gce_key
          chmod 600 /tmp/gce_key

      # 3. Copy the entire repository to the GCE VM (user "demo" on ${{ secrets.GCE_IP }})
      - name: Copy code to GCE VM
        run: |
          rsync -avz --delete \
            -e "ssh -i /tmp/gce_key -o StrictHostKeyChecking=no" \
            . \
            demo@${{ secrets.GCE_IP }}:/home/demo/Automation-Tests

      # 4. SSH into the VM and install dependencies, then run the Gradle tests
      - name: Run tests on GCE VM
        run: |
          ssh -i /tmp/gce_key -o StrictHostKeyChecking=no demo@${{ secrets.GCE_IP }} << 'EOF'
            set -e

            # Navigate into the copied repo
            cd /home/demo/Automation-Tests

            # Ensure Gradle wrapper is executable
            chmod +x gradlew

            # 4.1 Install JDK 17, Chrome, ChromeDriver, and other prerequisites
            sudo apt-get update -y
            sudo apt-get install -y openjdk-17-jdk git unzip curl

            # Install Google Chrome
            curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update -y
            sudo apt-get install -y google-chrome-stable

            # Install matching ChromeDriver
            CHROME_MAJOR=$(google-chrome --product-version | cut -d '.' -f1)
            DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR")
            wget -q "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip" -O /tmp/chromedriver.zip
            unzip /tmp/chromedriver.zip -d /tmp
            sudo mv /tmp/chromedriver /usr/local/bin/chromedriver
            sudo chmod +x /usr/local/bin/chromedriver

            # 4.2 Run your Gradle tasks (API, Web UI, and general tests)
            ./gradlew testApi
            ./gradlew testWeb
            ./gradlew test

            exit 0
          EOF

      # 5. Remove the temporary SSH key
      - name: Cleanup SSH key
        run: rm -f /tmp/gce_key
